-- TABLE T_ENVIRONMENTS
CREATE TABLE T_ENVIRONMENTS (
  ID NUMBER(8) NOT NULL,
  ENVIRONMENT VARCHAR2(256) NOT NULL,
  APPLICATION VARCHAR2(256) NOT NULL,
  VERSION VARCHAR2(64),
  STATUS NUMBER(1)
);

ALTER TABLE T_ENVIRONMENTS ADD CONSTRAINT PK_ENVIRONMENTS PRIMARY KEY(ID);
ALTER TABLE T_ENVIRONMENTS ADD CONSTRAINT UNIQUE_ENVIRONMENTS UNIQUE(ENVIRONMENT,APPLICATION);
